GET https://localhost:7114/api/peliculas

###
GET https://localhost:7114/api/peliculas/2

###
POST https://localhost:7114/api/peliculas 
Content-Type: application/json

{
"titulo": "Spiderman 3",
"sinopsis": "el joven se vuelve emo",
"anio": 2024,
"poster": "Sin poster",
"categorias": [2, 3]
}

###

PUT https://localhost:7114/api/peliculas/16
Content-Type: application/json

{
"peliculaid": 16,
"titulo": "Paw Patrol: La Súper Película",
"
sinopsis": "Un meteorito mágico aterriza en Adventure City y otorga superpoderes a los cachorros de PAW Patrol,",
"anio": 2024,
"poster": "https://m.media-amazon.com/images/M/MV5BMGI4NTN1ODItMGJlZ1000TIWLT1kM2ItMWFkZjJhZDIzMDc3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0.",
"categorias": [1, 2, 3]
}
###

DELETE https://localhost:7114/api/peliculas/16